[workspace]
members = ["crates/*"]
resolver = "2"

[profile.release]
opt-level = 3
lto = "thin"

[profile.debug-lite]
inherits = "dev"
incremental = false
opt-level = 0
debug = 1
lto = "off"

[profile.release-lite]
inherits = "release"
opt-level = 2

[profile.debug-opt]
inherits = "release"
debug = 2
debug-assertions = true
incremental = true

[profile.docker]
inherits = "release"
# strip = "symbols" # Not supported in the workspace toolchain version

[patch.crates-io]
solana-transaction-status = { git = 'https://github.com/step-finance/agave', rev = "aceb486fd2909fd533a775f485fea585a78b435a" }
solana-transaction-status-client-types = { git = 'https://github.com/step-finance/agave', rev = "aceb486fd2909fd533a775f485fea585a78b435a" }
agave-geyser-plugin-interface = { git = 'https://github.com/step-finance/agave', rev = "aceb486fd2909fd533a775f485fea585a78b435a" }
solana-metrics = { git = 'https://github.com/step-finance/agave', rev = "aceb486fd2909fd533a775f485fea585a78b435a" }
solana-zk-token-sdk = { git = 'https://github.com/step-finance/agave', rev = "aceb486fd2909fd533a775f485fea585a78b435a" }

# solana-transaction-status = { path = "../agave/transaction-status" }
# solana-transaction-status-client-types = { path = "../agave/transaction-status-client-types"}
# agave-geyser-plugin-interface = { path = "../agave/geyser-plugin-interface" }
# solana-metrics = { path = "../agave/metrics" }
# solana-zk-token-sdk = { path = "../agave/zk-token-sdk" }
