version: 2.1

orbs:
  docker: circleci/docker@2.4.0
  aws-ecr: circleci/aws-ecr@9.0.1
  aws-cli: circleci/aws-cli@4.1.1

jobs:
  build-and-push-image:
    machine:
      image: ubuntu-2204:2022.04.2
      resource_class: xlarge
    steps:
      - checkout
      - aws-cli/setup
      - aws-ecr/ecr_login:
          region: eu-north-1
      - docker/build:
          image: stepfinance/step-geyser-plugin
          tag: ${CIRCLE_BRANCH},${CIRCLE_BRANCH}-<< pipeline.number >>,${CIRCLE_BRANCH}-<< pipeline.number >>-${CIRCLE_SHA1}
      - run:
          name: "Docker Logout"
          command: docker logout
      - run:
          name: "Docker Login as stepfinance"
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - docker/push:
          image: stepfinance/step-geyser-plugin
          tag: ${CIRCLE_BRANCH},${CIRCLE_BRANCH}-<< pipeline.number >>,${CIRCLE_BRANCH}-<< pipeline.number >>-${CIRCLE_SHA1}

workflows:
  publish-geyser-plugin:
    jobs:
      - build-and-push-image:
          context: aws-account
          filters:
            branches:
              only:
                - step-release
